# Generated by Django 2.1 on 2018-10-10 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='组名称')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('describe', models.CharField(max_length=50, verbose_name='组描述')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='菜单名称')),
                ('fid', models.IntegerField(verbose_name='fid')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='url')),
                ('auth', models.SmallIntegerField(verbose_name='认证id')),
                ('sort', models.IntegerField(verbose_name='排序id')),
                ('hide', models.SmallIntegerField(verbose_name='是否隐藏')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='图标')),
                ('level', models.SmallIntegerField(verbose_name='level')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('describe', models.CharField(max_length=50, verbose_name='部门描述')),
            ],
        ),
        migrations.CreateModel(
            name='Renewmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=32)),
                ('program', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('dates', models.DateField(null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('res', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Saltgroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=32)),
                ('program', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saltopera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=32)),
                ('program', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('wk', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('res', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='账号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password_hash', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('reg_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('in_ip', models.CharField(max_length=20, null=True, verbose_name='登陆IP')),
                ('up_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itom.Group', verbose_name='组')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itom.Org', verbose_name='部门')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='menu',
            field=models.ManyToManyField(blank=True, to='itom.Menu', verbose_name='所具有的权限'),
        ),
    ]
