# Generated by Django 2.1 on 2018-08-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=32)),
                ('program', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('dates', models.DateField(null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=64)),
            ],
        ),
    ]
