# Generated by Django 2.1 on 2018-11-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fengbo_Bandwidth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Dtime', models.BigIntegerField()),
                ('Week', models.CharField(max_length=32)),
                ('Usernum', models.IntegerField()),
                ('Anchornum', models.IntegerField()),
                ('Wangsunum', models.IntegerField(null=True)),
                ('Upbindwidth', models.FloatField()),
                ('Downbindwidth', models.FloatField()),
            ],
        ),
    ]
