# Generated by Django 2.1 on 2018-11-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinaShow_AvsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.IntegerField()),
                ('PointTime', models.CharField(max_length=25)),
                ('Week', models.CharField(max_length=25)),
                ('Avs_Big_Num', models.IntegerField()),
                ('Avs_Over_Num', models.IntegerField()),
                ('Avs_General_Num', models.IntegerField()),
                ('Mic_Big_Num', models.IntegerField()),
                ('Mic_Over_Num', models.IntegerField()),
                ('Mic_General_Num', models.IntegerField()),
                ('Mic_Vip_Num', models.IntegerField()),
                ('Traffic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SinaShow_Bandwidth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.IntegerField()),
                ('Week', models.CharField(max_length=15)),
                ('SHOW_JIAXING', models.IntegerField()),
                ('SHOW_NingBo', models.IntegerField()),
                ('SHOW_BaoJi', models.IntegerField()),
                ('SHOW_KS', models.IntegerField()),
                ('SHOW_HangZhou', models.IntegerField()),
                ('SHOW_GanSu', models.IntegerField()),
                ('SHOW_HG', models.IntegerField()),
                ('SHOW_ZhengZhou', models.IntegerField()),
                ('SHOW_JinHua', models.IntegerField()),
                ('SHOW_ChangChun', models.IntegerField()),
                ('SHOW_ChangZhi', models.IntegerField()),
                ('SHOW_JinHua1', models.IntegerField()),
                ('SHOW_JiaXing1', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SinaShow_MaxUserTraffic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.IntegerField()),
                ('Week', models.CharField(max_length=15)),
                ('morn_useridnum', models.IntegerField()),
                ('morn_traffic', models.IntegerField()),
                ('after_useridnum', models.IntegerField()),
                ('after_traffic', models.IntegerField()),
                ('morn_time', models.CharField(max_length=25)),
                ('after_time', models.CharField(max_length=25)),
            ],
        ),
    ]
